[package]
name = "tool-sync"
version = "0.2.0"
authors = ["Dmitrii Kovanikov <kovanikov@gmail.com>"]
license = "MPL-2.0"
description = """
tool-sync is a CLI tool that manages installation of other CLI tools from GitHub
Releases by downloading binaries and storing them in a local directory.
"""
readme = "README.md"
homepage = "https://github.com/chshersh/tool-sync"
repository = "https://github.com/chshersh/tool-sync"
keywords = ["cli", "sync", "download", "tools"]
categories = ["command-line-utilities"]
edition = "2024"

[[bin]]
name = "tool"
path = "src/main.rs"

[dependencies]
# config
toml = { version = "0.8", default-features = false, features = ["parse"] }

# serde
facet = { git = "https://github.com/facet-rs/facet", branch = "main", default-features = false }
facet-derive = { git = "https://github.com/facet-rs/facet", branch = "main", default-features = false }
facet-pretty = { git = "https://github.com/facet-rs/facet", branch = "main", default-features = false }
facet-toml = { git = "https://github.com/facet-rs/facet", branch = "main", default-features = false, features = ["rich-diagnostics"] }
facet-json = { git = "https://github.com/facet-rs/facet", branch = "main", default-features = false, features = ["rich-diagnostics"] }

# UX
clap = { version = "4", default-features = false, features = ["derive"] }
clap_complete = { version = "4", default-features = false }

console = { version = "0.15", default-features = false }
indicatif = { version = "0.17", default-features = false }

# fetch
ureq = { version = "3", default-features = false, features = ["gzip", "platform-verifier", "rustls"] }

# extract
zip = { version = "2", default-features = false, features = ["deflate"] }
deko = { version = "0", default-features = false, features = ["flate2", "xz"] }
tar = { version = "0.4", default-features = false }

# search
dirs = { version = "6", default-features = false }
shellexpand = { version = "3", default-features = false, features = ["base-0", "tilde"] }
tempfile = { version = "3", default-features = false }
