[package]
name = "tool-sync"
version = "0.4.0"
authors = ["Dmitrii Kovanikov <kovanikov@gmail.com>"]
license = "MPL-2.0"
description = """
tool-sync is a CLI tool that manages installation of other CLI tools from GitHub
Releases by downloading binaries and storing them in a local directory.
"""
readme = "README.md"
homepage = "https://github.com/chshersh/tool-sync"
repository = "https://github.com/chshersh/tool-sync"
keywords = ["cli", "sync", "download", "tools"]
categories = ["command-line-utilities"]
edition = "2024"

[[bin]]
name = "tool"
path = "src/main.rs"

[dependencies]
# config
toml = { version = "0.9", default-features = false, features = ["parse", "serde"] }

# serde
facet = { version = "0.29", default-features = false }
facet-pretty = { version = "0.29", default-features = false }
facet-json = { version = "0.29", default-features = false, features = ["rich-diagnostics"] }
facet-toml = { version = "0.25", default-features = false, features = ["rich-diagnostics"] }

# UX
facet-args = { version = "0.29", default-features = false, features = ["rich-diagnostics"] }

console = { version = "0.16", default-features = false }
indicatif = { version = "0.18", default-features = false }

# fetch
ureq = { version = "3", default-features = false, features = ["gzip", "platform-verifier", "rustls"] }

# extract
zip = { version = "6", default-features = false, features = ["deflate"] }
deko = { version = "0", default-features = false, features = ["flate2", "xz"] }
tar = { version = "0.4", default-features = false }

# search
shellexpand = { version = "3", default-features = false, features = ["base-0", "tilde"] }
tempfile = { version = "3", default-features = false }
